### ISSUE TITLE
CheckTypes - external type of unbehaved variable

### ISSUE THREAD

**Issue by DanielTrivelli** [DanielTrivelli/decmore#7]
Only python standard types are behaved, causing an evaluation error when containing external types.

Example:

```
test_func(var1: pd.DataFrame):

    """
      raises: 

         Traceback (most recent call last):
           File "C:\Users\user\Desktop\projects\decorators\test\test.py", line 67, in <module>
             test_func('')
           File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\decmore\param_type.py", line 55, in wrapper
             error_string += self.error_constructor(
           File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\decmore\param_type.py", line 42, in error_constructor
             param_type = eval(param_type)
           File "<string>", line 1, in <module>
         NameError: name 'pandas' is not defined

    """

```

**Comment by DanielTrivelli** [comment]
Status: On Hold

Deprioritized due to a bug in BaseDecorator that affects decorators that can be used in classes

Related issues:

[#8](https://github.com/DanielTrivelli/decmore/issues/8) - BaseDecorator - injecting radar function into properties
[#9](https://github.com/DanielTrivelli/decmore/issues/9) - BaseDecorator - AttributeError when passing parameters without **
