### ISSUE TITLE
BaseDecorator - injecting radar function into properties

### ISSUE THREAD

**Issue by DanielTrivelli** [DanielTrivelli/decmore#8]
Example:

```
from decmore import Profiler

@Profiler()
class Test:
   prop1 = 1
   
   def __init__(self):
      ...

   """ 
    raises:
		Traceback (most recent call last):
	  File "C:\Users\User\AppData\Roaming\JetBrains\PyCharmCE2022.3\scratches\scratch_1.py", line 5, in <module>
		class Test:
	  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\decmore\default.py", line 81, in __call__
		return self.update_instance(instance)
	  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\decmore\default.py", line 66, in update_instance
		self.__injection()
	  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\decmore\default.py", line 49, in __injection
		if '@staticmethod' in getsource(this_method):
	  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 1147, in getsource
		lines, lnum = getsourcelines(object)
	  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 1129, in getsourcelines
		lines, lnum = findsource(object)
	  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 940, in findsource
		file = getsourcefile(object)
	  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 817, in getsourcefile
		filename = getfile(object)
	  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 797, in getfile
		raise TypeError('module, class, method, function, traceback, frame, or '
	TypeError: module, class, method, function, traceback, frame, or code object was expected, got int

   """


```

**Comment by DanielTrivelli** [comment]
Waiting to go up along with issue [#10 tests](https://github.com/DanielTrivelli/decmore/issues/10)
