### ISSUE TITLE
BaseDecorator - AttributeError when passing parameters without **

### ISSUE THREAD

**Issue by DanielTrivelli** [DanielTrivelli/decmore#9]
Example:

```
from traceback import format_exc

@Profiler()
class Test:
    def __init__(self):
        ...

    def get(self, **kwargs):
        print(kwargs)

    def post(self, **kwargs):
        print(kwargs)


if __name__ == '__main__':
    s = Test()
    s.get(**{'a': 1, 'b': 2})
    """ return: 
       
      {'a': 1, 'b': 2}
         4 function calls in 0.000 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.print}
        1    0.000    0.000    0.000    0.000 C:\Users\user\Desktop\projects\decorators\test\old\test.py:13(get)
        1    0.000    0.000    0.000    0.000 base_radar:1(base_radar)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}

    """

    try:
        s.get('test')
    except AttributeError as ex:
        print(format_exc())
 
      """raises:
 
	Traceback (most recent call last):
	  File "C:\Users\user\Desktop\projects\decorators\test\old\test.py", line 24, in <module>
		s.get('test')
	  File "C:\Users\user\Desktop\projects\decorators\test\old\profiler_dec.py", line 22, in wrapper
		retval = func(*args, **kwargs)
	  File "base_radar", line 3, in base_radar
		from typing import Any, Callable
	AttributeError: 'str' object has no attribute '_traced_methods'

      """


```

**Comment by DanielTrivelli** [comment]
Waiting to go up along with issue [#10 tests](https://github.com/DanielTrivelli/decmore/issues/10)
